---
- name: Provision Minecraft NPC
  hosts: localhost
  tasks:

    # From https://github.com/Automattic/node-canvas?tab=readme-ov-file#compiling
    # Alpine equivalent of: build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
    - name: Install node-canvas build dependency packages
      community.general.apk:
        name:
          - build-base
          - g++
          - pkgconf
          - cairo-dev
          - pango-dev
          - jpeg-dev
          - giflib-dev
          - librsvg-dev
          - pixman-dev
        state: present
        update_cache: true

    - name: Install minecraft-npc node.js package
      community.general.npm:
        name: minecraft-npc
        version: '{{ minecraft_npc_version }}'
        global: true
